### PR TITLE
[EX-36] Wrapped await promises

### PR DESCRIPTION
**Pull request by Arabadzhiew**
Closes EX-36

### CODE REVIEW

**Review by petya0111 — APPROVED** [review]

**Review by JordanRad — COMMENTED** [review]
Plaese, pay attention to the controllers as well, they still contain unwrapped await calls

**Review by JordanRad — CHANGES_REQUESTED** [review]
All controllers methods should be wrapped as well

**Comment by petya0111** [comment]
Аз съм правила и с rxjs то е подобно на функционалността await и става без try catch?
import { firstValueFrom, throwError} from 'rxjs';
return firstValueFrom(/*[line of the execution]*/)
        .then(response => {
         .catch(error => {
          throwError(() => error).pipe(first()).subscribe();
        });

@JordanRad   @Arabadzhiew  ?

**Comment by petya0111** [comment]
Имаме ли шанс да обърнем заявките към бекенда са са с rxjs и subscription ? @Arabadzhiew  @JordanRad

**Comment by Arabadzhiew** [comment]
> All controllers methods should be wrapped as well

Resolved in the latest commit.

**Review by petya0111 — APPROVED** [review]

**Review by JordanRad — APPROVED** [review]

**Pull request merged**
