### PR TITLE
markdown description of the project

### PR DESCRIPTION
**Pull request by petya0111**
Open https://github.com/Exordium-Project/e-shop/blob/md-file-presentation/README.md 
and share your ideas about great description of our project.

### CODE REVIEW

**Review by JordanRad — APPROVED** [review]
Great work! Seems organized and understandable.

**Review by IvayloSlavchev — APPROVED** [review]
Great job, @petya0111!

**Review by fbozhkov — APPROVED** [review]
Nice update to the README!

**Comment by Arabadzhiew** [comment]
@petya0111 I don't see `Express` mentioned anywhere in the readme. Could you please add that as well, as I think it's a meaningful part of our backend tech-stack.

**Pull request merged**
