### PR TITLE
Footer component

### PR DESCRIPTION
**Pull request by petya0111**
Acceptance criteria:
- Add Footer component with copyright and name of the project

### CODE REVIEW

**Comment by fbozhkov** [comment]
There seems to be a gap on the right side of the footer. Somehow it is not in full width of the page. 

image

Nice idea including the discord invite link. I think the buttons would be better off without the purple background colour. You can also use a discord icon before the button.

**Review by IvayloSlavchev — COMMENTED** [review]
I think you should set the links next to the logo and title, because there is a lot of empty space.

**Review by JordanRad — APPROVED** [review]
Good work

**Comment by petya0111** [comment]
> I think you should set the links next to the logo and title, because there is a lot of empty space.

This view is on tablet, on desktop all are on one line.

**Review by IvayloSlavchev — APPROVED** [review]
Good job, @petya0111!

**Review by Arabadzhiew — APPROVED** [review]

**Review by fbozhkov — APPROVED** [review]

**Pull request merged**
