### PR TITLE
task#22-\Add a Special component

### PR DESCRIPTION
**Pull request by Stanislav001**

### CODE REVIEW

**Review by JordanRad — APPROVED** [review]
Looks good to me

**Review by petya0111 — CHANGES_REQUESTED** [review]
Please update (rebase) branch with latest dev changes, apply logic for opening special component and ensure everything is responsive.

**Review by petya0111 — APPROVED** [review]
Everything seems to work fine :)

**Review by petya0111 — CHANGES_REQUESTED** [review]
Please try to align the special component with design guidelines. I have given an example in this issue https://github.com/Exordium-Project/e-shop/issues/30

**Review by petya0111 — APPROVED** [review]

**Pull request merged**
