### PR TITLE
Refactor catalog

### PR DESCRIPTION
**Pull request by IvayloSlavchev**
We have to fetch properties about Accordions. Also we need to remove the old images and set new that will not have copyright problems and if need to resize them.

### CODE REVIEW

**Comment by petya0111** [comment]
@IvayloSlavchev I think we can search for images with copyright that allow using it.

https://creativecommons.org/licenses/by-nc-sa/2.5/bg/

**Comment by IvayloSlavchev** [comment]
> @IvayloSlavchev I think we can search for images with copyright that allow using it. image image

Yes, the new Google's feature shows which image requires license and who doesn't

**Review by fbozhkov — COMMENTED** [review]
I have some styling comments:

- Add some margin from the header
- Make the filter sidebar smaller (thinner) also the font-size used there could be smaller aswell
- Remove the outline and shadow of the Accordion component ( You can check the styling of DeliveryAccordion under product-page)
- Think about mobile view - make the sideber hide itself on smaller displays. You can also implement a toggle switch for it like in the mockup.

**Review by JordanRad — APPROVED** [review]
Looks good to me

**Review by petya0111 — APPROVED** [review]
Excellent work!

**Pull request merged**
